version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
     - pip install -r requirements.txt

  build:
    commands:
      - python3 setup.py sdist bdist_wheel

artifacts:
  files:
    - dist/*
  name: sample-python-app-artifacts
  bucket-name: sample-python-app-codebuild